sudo: required

language: node_js
node_js:
  - "5.4"

services:
  - docker

before_install:
  - docker build -t cheese-nerd:dev -f ./src/config/.DevDockerfile .
  - docker run cheese-nerd:dev gluestick test -S
